version: "3"
services:
  postgres:
    image: postgres:14
    container_name: world_db
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  get_data:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/get_data.py
    container_name: get_data_app
    env_file: '.env'
    depends_on: 
      - postgres
    volumes:
      - .:/app
  
  print_data:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/print_data.py
    container_name: print_data_app
    env_file: '.env'
    depends_on: 
      - postgres
    volumes:
      - .:/app

volumes:
  pg_data:
