version: "3"
services:
  postgres:
    image: postgres:14
    container_name: world_db
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  get_data:
    build:
      context: .
    command: python3 src/script/script_table_name.py
    image: world_population
    container_name: get_data_app
    env_file: '.env'
    depends_on: 


      - inint.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pg_data:
